ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ward VARCHAR(255),
    ADD COLUMN IF NOT EXISTS district VARCHAR(255),
    ADD COLUMN IF NOT EXISTS city VARCHAR(255),
    ADD COLUMN IF NOT EXISTS postal_code VARCHAR(50);

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS shipping_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS shipping_phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS shipping_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS shipping_ward VARCHAR(255),
    ADD COLUMN IF NOT EXISTS shipping_district VARCHAR(255),
    ADD COLUMN IF NOT EXISTS shipping_city VARCHAR(255),
    ADD COLUMN IF NOT EXISTS shipping_note VARCHAR(255);
